[package]
name = "tmprs"
version = "0.1.1"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
rodio = "0.19.0"

[source.crates-io]
replace-with = 'vendored-sources'

[source.vendored-sources]
directory = "vendor"

